name: Amazon Discount Finder

on:
  schedule:
    # 毎日 9:00と18:00（UTC）に実行
    - cron: '0 0,9 * * *'
  workflow_dispatch:
    # 手動実行用

jobs:
  find-discounts:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tweepy python-dotenv requests
    
    - name: Run discount finder
      env:
        PA_API_KEY: ${{ secrets.PA_API_KEY }}
        PA_API_SECRET: ${{ secrets.PA_API_SECRET }}
        PARTNER_TAG: ${{ secrets.PARTNER_TAG }}
        TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
        TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
        TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
        TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        THREADS_ACCESS_TOKEN: ${{ secrets.THREADS_ACCESS_TOKEN }}
        THREADS_USER_ID: ${{ secrets.THREADS_USER_ID }}
      run: python amazon_discount_finder.py
    
    - name: Commit changes
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'actions@github.com'
        git add discount_results.json
        git diff --quiet && git diff --staged --quiet || git commit -m "Update discount results [automated]"
        git push
